### PR TITLE
Add info about size of the client

### PR DESCRIPTION
**Pull request by myshov**

### CODE REVIEW

**Comment by myshov** [comment]
Spelling check:
✗ /home/runner/work/docs/docs/README.md 457 ms

Typos: 3
1. 35kB (13:24)
2. 10kB (13:32)
3. gzipped (13:37)

**Comment by myshov** [comment]
It seems that Github can't recognize updates in branch with merged changes. So I need to close this pr and open a new one

**Comment by myshov** [comment]
I've just forgot to merge that stuff :D

**Comment by ai** [comment]
1. Let's use one metric (I am suggesting gzipped, but I am open for other opinions) just now that it is `minified and gzipped` metric. People do not like to choose and could be confused with two metrics.
2. Let's add link to proofs. You can use link to Size Limit config at Logic Client `package.json`.

**Comment by myshov** [comment]
1. I also think that gzipped is enough. I will fix it
2. Do you mean this https://github.com/logux/client/blob/master/package.json#L89?

**Comment by ai** [comment]
Yeap

**Comment by myshov** [comment]
Sorry for delay I've just fixed readme + squashed all commits in this pr

**Comment by ai** [comment]
Thanks =^_^=

**Pull request merged**
